name: 'Deploy'

on:
  pull_request:
    branches:
      - 'main'
jobs:
  deploy:
    runs-on: 'ubuntu-latest'
    timeout-minutes: 10
    permissions:
      contents: 'read'
      id-token: 'write'
    steps:
      - uses: 'actions/checkout@v3'
      - id: 'auth'
        uses: 'google-github-actions/auth@v0'
        with:
          workload_identity_provider: '${{secrets.WORKLOAD_IDENTITY_PROVIDER}}'
          service_account: '${{secrets.SERVICE_ACCOUNT}}'
      - name: 'Setup GCP client'
        uses: 'google-github-actions/setup-gcloud@v0'
      - name: 'Deploy to GCP'
        run: 'make deploy'
